// src/routes/components/radio/index.tsx
import {Column} from "@qinetik/anique/column";
import {DocContainer} from "../../../components/common/layout/DocContainer";
import {ComponentExample} from "../../../solid/components/ComponentExample";
import BasicRadioExample from "./examples/BasicRadioExample";
import SizeVariationsExample from "./examples/SizeVariationsExample";
import RadioLabelDescriptionExample from "./examples/RadioLabelDescriptionExample";
import DisabledRadioExample from "./examples/DisabledRadioExample";

export default function RadioPage() {
    return (
        <DocContainer>
            <Column>
                <h1>Basic Radio</h1>
                <ComponentExample component={BasicRadioExample}/>
                <h1>Size Variations</h1>
                <ComponentExample component={SizeVariationsExample}/>
                <h1>Radio with Label & Description</h1>
                <ComponentExample component={RadioLabelDescriptionExample}/>
                <h1>Disabled Radio</h1>
                <ComponentExample component={DisabledRadioExample}/>
            </Column>
        </DocContainer>
    )
}

// demo/src/routes/radio.tsx
import {PageContainer} from "../components/PageContainer";
import {H1} from "@qinetik/anique/headings";
import {Card} from "@qinetik/anique/card";
import {Radio, LabeledRadio} from "@qinetik/anique/radio";
import {createSignal} from "solid-js";
import {Column} from "@qinetik/anique/column";

function BasicRadioExample() {
    const [isChecked, setIsChecked] = createSignal(false)
    return (
        <Card>
            <Radio
                isChecked={isChecked}
                onChange={setIsChecked}
            />
        </Card>
    )
}

function RadioWithLabel() {
    const [isChecked, setIsChecked] = createSignal(false)
    return (
        <Card>
            <LabeledRadio
                isChecked={isChecked}
                onChange={setIsChecked}
                label={"Terms & Services"}
            />
        </Card>
    )
}

function RadioWithLabelDescription() {
    const [isChecked, setIsChecked] = createSignal(false)
    return (
        <Card>
            <LabeledRadio
                isChecked={isChecked}
                onChange={setIsChecked}
                label={"Terms & Services"}
                description={"I agree to terms & services of this company"}
            />
        </Card>
    )
}

export default function RadioPage() {

    return (
        <PageContainer>
            <Column>
                <H1>Basic Radio</H1>
                <BasicRadioExample/>
                <H1>Radio with Label</H1>
                <RadioWithLabel/>
                <H1>Radio with Label & Description</H1>
                <RadioWithLabelDescription/>
            </Column>
        </PageContainer>
    )
}
