// packages/anique/src/appbar/index.tsx
import {styled} from "@qinetik/emotion";
import {JSX, splitProps} from "solid-js";

export interface AppBarProps extends JSX.HTMLAttributes<HTMLDivElement> {
    navIcon?: any
    title: any
    actions?: any
}

const AppBarContainer = styled('div')`
  width: 100%;
  display: flex;
  flex-direction: row;
  align-items: center;
  box-sizing: border-box;
  padding: 0 1em;
  height: 4em;
`

const AppBarNavIcon = styled('div')`
  margin-right: 1rem;
`

const AppBarTitle = styled("h3")`
  flex : 1;
`

const AppBarActions = styled("div")`

`

export function AppBar(props: AppBarProps) {
    return (
        <AppBarContainer {...splitProps(props, ["navIcon", "title", "actions"])[1]}>
            {props.navIcon != null ? (
                <AppBarNavIcon>
                    {props.navIcon}
                </AppBarNavIcon>
            ) : null}
            <AppBarTitle>
                {props.title}
            </AppBarTitle>
            {props.actions != null ? (
                <AppBarActions>
                    {props.actions}
                </AppBarActions>
            ) : null}
        </AppBarContainer>
    )
}

// lib/src/appbar/AppBar.tsx
import {styled} from "@qinetik/emotion";
import {H3, H6} from "../headings";

export interface AppBarProps {
    navIcon?: () => any
    title: string
}

const AppBarContainer = styled('div')`
    display: flex;
    flex-direction: row;
    height: 4em;
    background: ${p => p.theme.colors.bg100};
`

const NavIconContainer = styled('div')`

`

const TitleContainer = styled(H3)`
    margin-left: 1rem;
`

export function AppBar(props: AppBarProps) {
    return (
        <AppBarContainer>
            {props.navIcon != null ? (
                <NavIconContainer>
                    {props.navIcon()}
                </NavIconContainer>
            ) : null}
            <TitleContainer>
                {props.title}
            </TitleContainer>
        </AppBarContainer>
    )
}
