// src/routes/components/switch.tsx
import {Card, Column, Headline} from "@qinetik/anique";
import {ToggleSwitch} from "@qinetik/anique/toggleswitch";
import {createSignal} from "solid-js";
import {DocContainer} from "../../components/common/layout/DocContainer";

export default function SwitchPage() {
    const [isChecked, setIsChecked] = createSignal(false)
    return (
        <DocContainer>
            <Column gap={"1em"}>
                <Headline>ToggleSwitch</Headline>
                <Card>
                    <ToggleSwitch
                        checked={isChecked()}
                        onChange={(e) => {
                            setIsChecked(e.currentTarget.checked)
                        }}
                    />
                </Card>
                <h2>Disabled</h2>
                <Card>
                    <ToggleSwitch
                        disabled
                        checked={isChecked()}
                    />
                </Card>
            </Column>
        </DocContainer>
    )
}

// src/routes/components/switch/index.tsx
import {Column, Headline} from "@qinetik/anique";
import {ComponentExample} from "../../../solid/components/ComponentExample";
import BasicSwitchExample from "./examples/BasicSwitchExample";
import DisabledSwitchExample from "./examples/DisabledSwitchExample";
import {DocContainer} from "../../../components/common/layout/DocContainer";

export default function SwitchPage() {
    return (
        <DocContainer>
            <Column gap={"1em"}>
                <Headline>ToggleSwitch</Headline>
                <ComponentExample component={BasicSwitchExample}/>
                <h2>Disabled</h2>
                <ComponentExample component={DisabledSwitchExample}/>
            </Column>
        </DocContainer>
    )
}
